version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosecoco_laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - storage:/var/www/storage
    networks:
      - rosecoco_laravel_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: rosecoco_laravel_nginx
    restart: unless-stopped
    ports:
      - 8000
      - 80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rosecoco_laravel_network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosecoco_laravel_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - rosecoco_laravel_network

volumes:
  storage:

networks:
  rosecoco_laravel_network:
    driver: bridge
