version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rosecoco-app
    container_name: rosecoco-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - rosecoco

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - rosecoco

networks:
  rosecoco:
    driver: bridge
